apiVersion: v1
kind: Service
metadata:
  name: lifecycle-webhook-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- include "common.labels.standard" ( dict "context" . ) | nindent 4 }}
spec:
  type: {{ .Values.lifecycleWebhookService.type }}
  selector:
    control-plane: lifecycle-operator
  {{- include "common.selectorLabels"  ( dict "context" . )  | nindent 4 }}
  ports:
	{{- .Values.lifecycleWebhookService.ports | toYaml | nindent 2 -}}