apiVersion: v1
kind: ServiceAccount
metadata:
  name: certificate-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    {{- include "common.labels.standard" ( dict "context" $ ) | nindent 4 }}
 {{- if or .Values.annotations .Values.global.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.annotations .Values.global.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
